### PR TITLE
added script for running all tests

### PR DESCRIPTION
**Pull request by osblinnikov**

### CODE REVIEW

**Comment by osblinnikov** [comment]
test this please

**Comment by osblinnikov** [comment]
test this please

**Comment by osblinnikov** [comment]
test this please

**Comment by CompanybookServer** [comment]
cc

**Comment by osblinnikov** [comment]
test this please

**Comment by osblinnikov** [comment]
test this please

**Comment by osblinnikov** [comment]
test this please

**Review by khellan — APPROVED** [review]

**Pull request merged**
